.github/pull_request_template.md
This PR changes all occurrences of "merge request" to "pull request" in the pull request template.
* Closes
* Blocks
* Follows
* Precedes
* Related to
* Part of
* Composed of
=> Fix typos in pull request template

.github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/feature-request.yml
It is good practice to have templates for creating an issue.
On GitLab we had templates, but we need to add them also for GitHub.
I chose to try the Yaml style template, which should result in a nice questionnaire to create the template instead of dealing with the markdown version. I got that feature from the numpy repo: https://github.com/numpy/numpy/blob/main/.github/ISSUE_TEMPLATE/feature-request.yml?plain=1
* Closes
* Blocks
* Follows
* Precedes
* Related to
* Part of
* Composed of
=> Add GitHub issue template

README.md
This MR changes the path for the logos. Instead of using a specific commit hash, the main branch is used instead.
* Closes
* Blocks
* Follows
* Precedes
* Related to
* Part of
* Composed of
=> Use main branch for QUEENS logo

.github/workflows/build_documentation.yml, .github/workflows/tests_local.yml, CONTRIBUTING.md, README.md, pyproject.toml
This PR adds badges regarding our workflows and our coding environment to the README.md.
The first badge shows the status of the tests_local workflow on our main branch. In order for this badge to show "passing", this workflow needs to run on the main branch after a pull request, so the corresponding trigger is added to the workflow. In the future, this badge could show the status of our nightly workflow.
In addition, some outdated GitLab links are updated to the corresponding GitHub links.
* Closes
* Blocks
* Follows
* Precedes
* Related to
* Part of #82
* Composed of
=> Add badges to readme

.github/workflows/tests_local.yml
This PR (tries) to add the JUNIT pytest output of every action
* Closes
* Blocks
* Follows
* Precedes
* Related to
* Part of
* Composed of
=> feat(test_local.yml): upload junit report generated by pytest

CHANGELOG.md, CODE_OF_CONDUCT.md, CONTRIBUTING.md
This PR fixes (hopefully all of) the remaining broken links in our repo. It further fixes some typos I found in our markdown files.
* Closes #77 
* Blocks
* Follows
* Precedes
* Related to
* Part of
* Composed of
I went through all of our markdown files and checked the links. Additionally, I looked for occurrences of the word "gitlab" in our repo.
=> docs: fix broken links & typos

CONTRIBUTING.md, doc/README.md
Add a README with the instructions for the documentation build process
* Closes
* Blocks
* Follows
* Precedes
* Related to
* Part of
* Composed of
=> Add instructuions to build the documentation

doc/source/_ext/templates/intro.md.j2
When setting up a new installation, one usually wants to test, if it then works properly. This PR adds links to the testing page after the installation step.
=> docs: Describe post-installation testing

.github/workflows/tests_local.yml
This PR adds an action to check if the commit messages are in accordance with [conventional commits](https://www.conventionalcommits.org) (as mentioned in the CONTRIBUTING.md)
* Closes
* Blocks
* Follows
* Precedes
* Related to
* Part of
* Composed of
=> ci: add commit message check

queens/main.py
This PR adds logging information for users to consider using a Python script workflow.
* Closes
* Blocks
* Follows
* Precedes
* Related to
* Part of
* Composed of
=> refactor(main): add info for users to consider using the script workflow

.gitlab/.gitlab-ci.yml
For the scheduled nightly pipeline of the cluster test, we also need the rule `$CI_PIPELINE_SOURCE == "schedule"`. 
* Closes
* Blocks
* Follows
* Precedes
* Related to
* Part of
* Composed of
=> ci: fix workflow rules

doc/source/_ext/templates/overview.rst.j2, doc/source/_ext/templates/tutorials.rst.j2, queens/__init__.py, queens/data_processor/__init__.py, queens/distributions/__init__.py, queens/drivers/__init__.py, queens/example_simulator_functions/__init__.py, queens/external_geometry/__init__.py, queens/interfaces/__init__.py, queens/iterators/__init__.py, queens/models/__init__.py, queens/models/likelihood_models/__init__.py, queens/models/model.py, queens/models/surrogate_models/__init__.py, queens/parameters/__init__.py, queens/parameters/fields/__init__.py, queens/schedulers/__init__.py, queens/stochastic_optimizers/__init__.py, queens/utils/__init__.py, queens/variational_distributions/__init__.py, queens/visualization/__init__.py
This PR updates our package descriptions for the Packages tab (former Modules overview tab) in the documentation. The revisions were made in collaboration with @gilrrei.
* Closes
* Blocks
* Follows
* Precedes
* Related to
* Part of
* Composed of
=> Revise package descriptions

.github/workflows/tests_local.yml, tests/input_files/third_party/fourc/coarse_plate_dirichlet_template.dat, tests/input_files/third_party/fourc/solid_runtime_hex8.dat
This MR consists of two changes:
- Pull the main 4C image instead of the latest release
- Fix the 4C input files for the latest changes
* Closes
* Blocks
* Follows
* Precedes
* Related to
* Part of
* Composed of
=> Pull 4C main image and fix 4C input files

.github/workflows/tests_local.yml, .github/xml_summaries_to_md.py
Improve CI pytest summary, also adds coverage numbers
* Closes
* Blocks
* Follows
* Precedes
* Related to
* Part of
* Composed of
=> ci: add pytest summary

tests/input_files/third_party/fourc/coarse_plate_dirichlet_template.dat, tests/input_files/third_party/fourc/solid_runtime_hex8.dat, tests/integration_tests/fourc/test_fourc_mc.py, tests/integration_tests/fourc/test_fourc_mc_random_field_ensight.py
quickfix 4C input DAMPING parameter
* Closes
* Blocks
* Follows
* Precedes
* Related to
* Part of
* Composed of
=> fix: 4C input DAMPING parameter

.github/actions/create_python_environment/action.yml, queens/iterators/__init__.py, queens/iterators/reinforcement_learning.py, queens/models/__init__.py, queens/models/reinforcement_learning/__init__.py, queens/models/reinforcement_learning/reinforcement_learning.py, queens/models/reinforcement_learning/utils/__init__.py, queens/models/reinforcement_learning/utils/gymnasium.py, queens/models/reinforcement_learning/utils/stable_baselines3.py, requirements.in, requirements.txt, tests/integration_tests/python/test_reinforcement_learning_integration.py, tests/unit_tests/data_processors/test_txt_file.py, tests/unit_tests/iterators/test_reinforcement_learning.py, tests/unit_tests/models/test_reinforcement_learning.py
Addition of a module for conducting reinforcement learning (RL) experiments within the QUEENS framework. The implementation relies on the well-established `stable-baselines3` and `gymnasium` libraries, both published under the MIT licence, so an addition of these dependencies to QUEENS should not cause any legal problems.
-
The training of a reinforcement learning agent is generally difficult to test since the training incurs randomness not only on the level of the agent (i.e., the learning algorithm, usually some sort of neural network which is trained with stochastic gradient descant or variants thereof) but also on the side of the environment (encoding the problem to be solved). 
I've added multiple tests (unit tests and one integration test) which do not explicitly test against values …
=> Addition of Reinforcement learning (RL) module 

templates/jobscripts/fourc_charon.sh
The IMCS cluster Charon has received a substantial update, including a new operating system.
Consequently, the job script for the cluster must be adjusted to accommodate the latest modifications. 
* Closes
* Blocks
* Follows
* Precedes
* Related to
* Part of
* Composed of
I have tested the jobscript manually on the cluster.
=> Update charon jobscript template

queens/utils/io.py
Fix warning: `ResourceWarning: unclosed file <_io.BufferedReader name='...'> data = pickle.load(file_path.open("rb"))`
* Closes
* Blocks
* Follows
* Precedes
* Related to
* Part of
* Composed of
=> quickfix: unclosed pickle file

queens/iterators/_variational_inference.py, queens/iterators/bbvi.py, queens/iterators/reparameteriztion_based_variational.py, queens/iterators/sequential_monte_carlo_chopin.py, queens/models/_model.py, queens/models/bmfmc.py, queens/models/finite_difference.py, queens/models/likelihoods/_likelihood.py, queens/models/likelihoods/bmf_gaussian.py, queens/models/likelihoods/gaussian.py, queens/models/logpdf_gp.py, queens/models/reinforcement_learning/reinforcement_learning.py, queens/models/simulation.py, queens/models/surrogates/_surrogate.py, queens/utils/sequential_monte_carlo.py, tests/integration_tests/python/test_bbvi_iterator.py, tests/integration_tests/python/test_rpvi_iterator.py, tests/unit_tests/models/test_bmfmc.py, tests/unit_tests/models/test_model.py
This PR adds a model evaluation counter to the `Model` base class and removes the counting from some iterators.
* Closes #23
* Blocks
* Follows
* Precedes
* Related to
* Part of
* Composed of
=> Add model counter

README.md
Add global_settings context to README exmaple.
* Closes
* Blocks
* Follows
* Precedes
* Related to
* Part of
* Composed of
=> fix: add global_settings context to README exmaple

CONTRIBUTING.md, doc/README.md, tests/README.md
This PR updates the contributing and testing documentation of QUEENS.
* Closes
* Blocks
* Follows
* Precedes
* Related to
* Part of
* Composed of
=> Improve contributing and testing documentation

queens/iterators/adaptive_sampling.py, tests/integration_tests/python/test_constrained_gp_ip.py
Since the default workflow is now with a Python script and not with an input file, it is easier to provide initial training samples as an array instead of providing an iterator to generate initial training samples for the `AdaptiveSampling` Iterator. 
* Closes
* Blocks
* Follows
* Precedes
* Related to
* Part of
* Composed of
=> refactor: adaptive sampling iterator

.gitlab/.gitlab-ci.yml
Currently, 4C is built directly on the login nodes of the clusters during the test pipelines. This approach worked previously, but with the recent update to the charon cluster, executing builds on the login node is no longer possible.
This PR updates the cluster test pipeline to:
- Offload the 4C build to a scheduled SLURM job using srun
- Flexible resource allocation (CPU, time, partition) with variables
- Avoid overloading the login node, aligning with good HPC usage practices
Implementation Notes
- The SLURM job runs the exact same build commands as before (cmake + ninja)
- The SLURM configuration (time, CPUs, etc.) is integrated into the CI pipeline
- srun allows full logging and failure tracking straight to the gitlab runner
- only clone the latest commit on the default branch of 4C …
=> Move Cluster Build of 4C from Login Node to SLURM Job

tests/unit_tests/interfaces/test_bmfia_interface.py, tests/unit_tests/models/test_gaussian.py
As raised in https://github.com/queens-py/queens/discussions/188 by @phfranz, we have a couple of incorrect assertion statements in our test suite that can cause an AttributeError.
This PR fixes these statements.
* Closes
* Related to https://github.com/queens-py/queens/discussions/188
@phfranz
=> fix: AttributeError not a valid assertion

CITATION.cff, README.md
The QUEENS Paper is published as a preprint on arXiv.
This PR suggests updating the how to cite information in the README to start citing the paper. 
Once the paper is published in a peer-reviewed journal, we should update the information again.
* Closes
* Related to
=> Update how-to-cite with arXiv preprint of paper
